### ISSUE TITLE
Configuration-as-Code compatibility: cannot connect to containers using SSH

### ISSUE THREAD

**Issue by robincsmith** [KostyaSha/yet-another-docker-plugin#248]
When configuring this plugin using the [Configuration as Code](https://github.com/jenkinsci/configuration-as-code-plugin) plugin, SSH connections to containers are failing.

On closer inspection, it seems that the Yet Another Docker plugin is doing the following:
- ignoring the credentialsId defined in the `dockerComputerSSHLauncher` section
- adding a brand new SSH credential to Jenkins, containing no SSH key but specifying 'jenkins' as the relevant user (see attached images)
- using this new credential to manage the SSH connection to the build agent - which fails

```  
jenkins:
  # ...
  clouds:
  - docker:
      connector:
        serverUrl: "tcp://10.11.12.13:2375"
      containerCap: 5
      name: "docker-build-host-01"
      templates:
      - dockerContainerLifecycle:
          createContainer:
            bindAllPorts: false
            cpuShares: 512
            hostname: ""
            memoryLimit: 0
            privileged: true
            shmSize: 0
            tty: false
            volumes:
            - "/home/agent/.ssh:/home/agent/.ssh:ro"
            volumesString: "/home/agent/.ssh:/home/agent/.ssh:ro"
          image: "my.docker.registry.io/my-build-image:latest"
          pullImage:
            pullStrategy: PULL_NEVER
            registriesCreds:
            - registryAddr: "my.docker.registry.io"
              credentialsId: "registry-creds-defined-in-credentials-section"
          removeContainer:
            removeVolumes: false
        id: "12abcdef-3456-7890-abcd-123456789000"
        labelString: "docker-build-agent"
        launcher:
          dockerComputerSSHLauncher:
            sshConnector:
              credentialsId: "ssh-key-defined-in-credentials-section"
              maxNumRetries: 0
              port: 22
              retryWaitTime: 0
              sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        maxCapacity: 5
        osType: LINUX
        remoteFs: "/home/agent"

credentials:
  system:
    domainCredentials:
    - credentials:
      - dockerRegistryAuth:
          id:       "registry-creds-defined-in-credentials-section"
          scope:    GLOBAL
          description: "Jenkins credentials for my Docker registry"
          email:    "robin.smith@test.com"
          username: "robincsmith"
          password: "${somePassword}"
      - basicSSHUserPrivateKey:
          id:       "ssh-key-defined-in-credentials-section"
          scope:    GLOBAL
          description: "SSH private key used to connect to Docker build agents"
          username: "agent"
          passphrase: ""
          privateKeySource:
            directEntry:
              privateKey: "${privateKey}"
```

logs:
```
Feb 14, 2019 4:39:10 PM INFO com.github.kostyasha.yad.DockerCloud provision
Asked to provision load: '1', for: 'docker-build-agent' label
Feb 14, 2019 4:39:10 PM INFO com.github.kostyasha.yad.DockerCloud provision
Will provision 'my.docker.registry.io/my-build-image:latest', for label: 'docker-build-agent', in cloud: 'docker-build-host-01'
Feb 14, 2019 4:39:12 PM INFO com.github.kostyasha.yad.DockerCloud addProvisionedSlave
Provisioning 'my.docker.registry.io/my-build-image:latest' number '3' on 'docker-build-host-01'; Total containers: '3'
Feb 14, 2019 4:39:13 PM INFO com.github.kostyasha.yad.utils.HostAndPortChecker bySshWithEveryRetryWaitFor
SSH port is open on 10.11.12.13:43819
Feb 14, 2019 4:39:13 PM INFO com.github.kostyasha.yad.launcher.DockerComputerSSHLauncher getSSHLauncher
Creating slave SSH launcher for '10.11.12.13:43819'. Cloud: 'docker-build-host-01'. Template: 'my.docker.registry.io/my-build-image:latest'
Feb 14, 2019 4:39:13 PM WARNING hudson.plugins.sshslaves.SSHLauncher 
This constructor is deprecated and will be removed on next versions, please do not use it.
Feb 14, 2019 4:39:20 PM INFO hudson.slaves.NodeProvisioner$2 run
my.docker.registry.io/my-build-image:latest provisioning successfully completed. We have now 2 computer(s)
```
![screen shot 2019-02-14 at 16 43 08](https://user-images.githubusercontent.com/23170929/52803069-24e9f800-3079-11e9-86b0-612db01db1a2.png)
![screen shot 2019-02-14 at 16 42 57](https://user-images.githubusercontent.com/23170929/52803070-25828e80-3079-11e9-8711-acef2fa4ea93.png)
